package w3xyz.chronitecore.item;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroupEntries;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import org.quiltmc.qsl.item.setting.api.QuiltItemSettings;
import w3xyz.chronitecore.ChroniteCore;

public class ModItems {
	public static final Item CHRONITE = registerItem("chronite", new Item(new QuiltItemSettings()));
	public static final Item RAW_CHRONITE = registerItem("raw_chronite", new Item(new QuiltItemSettings()));
	public static final Item ION_SHARD = registerItem("ion_shard", new Item(new QuiltItemSettings()));
	public static final Item ION_DUST = registerItem("ion_dust", new Item(new QuiltItemSettings()));

	public static final Item AQUANITE = registerItem("AQUANITE", new Item(new QuiltItemSettings()));
	public static final Item LUMINITE = registerItem("LUMINITE", new Item(new QuiltItemSettings()));
	public static final Item SPARKSTONE = registerItem("SPARKSTONE", new Item(new QuiltItemSettings()));
	public static final Item GEMFORGE = registerItem("GEMFORGE", new Item(new QuiltItemSettings()));
	public static final Item EMBERITE = registerItem("EMBERITE", new Item(new QuiltItemSettings()));
	public static final Item GRAPHITE = registerItem("GRAPHITE", new Item(new QuiltItemSettings()));
	public static final Item SKYBLOOM = registerItem("SKYBLOOM", new Item(new QuiltItemSettings()));
	public static final Item AIRITE = registerItem("AIRITE", new Item(new QuiltItemSettings()));
	public static final Item FROZITE = registerItem("FROZITE", new Item(new QuiltItemSettings()));
	public static final Item GLOWNITE = registerItem("GLOWNITE", new Item(new QuiltItemSettings()));
	public static final Item SEANITE = registerItem("SEANITE", new Item(new QuiltItemSettings()));
	public static final Item LAVADITE = registerItem("LAVADITE", new Item(new QuiltItemSettings()));
	public static final Item ALLOYITE = registerItem("ALLOYITE", new Item(new QuiltItemSettings()));
	public static final Item SILVASTEEL = registerItem("SILVASTEEL", new Item(new QuiltItemSettings()));
	public static final Item GLOWPHITE = registerItem("GLOWPHITE", new Item(new QuiltItemSettings()));
	public static final Item SULFIRE = registerItem("SULFIRE", new Item(new QuiltItemSettings()));
	public static final Item AQUEOUSITE = registerItem("AQUEOUSITE", new Item(new QuiltItemSettings()));
	public static final Item INERTIUM = registerItem("INERTIUM", new Item(new QuiltItemSettings()));
	public static final Item VOLTASHARD = registerItem("VOLTASHARD", new Item(new QuiltItemSettings()));
	public static final Item STONEMOSS = registerItem("STONEMOSS", new Item(new QuiltItemSettings()));
	public static final Item ETHERIUM = registerItem("ETHERIUM", new Item(new QuiltItemSettings()));
	public static final Item TITANFORGE = registerItem("TITANFORGE", new Item(new QuiltItemSettings()));
	public static final Item METALLURGE = registerItem("METALLURGE", new Item(new QuiltItemSettings()));
	public static final Item CHROMALLOY = registerItem("CHROMALLOY", new Item(new QuiltItemSettings()));
	public static final Item MANASTEEL = registerItem("MANASTEEL", new Item(new QuiltItemSettings()));
	public static final Item COBALTITE = registerItem("COBALTITE", new Item(new QuiltItemSettings()));
	public static final Item MAGNETITE = registerItem("MAGNETITE", new Item(new QuiltItemSettings()));
	public static final Item ZINCRUSH = registerItem("ZINCRUSH", new Item(new QuiltItemSettings()));
	public static final Item LUNALITE = registerItem("LUNALITE", new Item(new QuiltItemSettings()));
	public static final Item GEOCRYSTAL = registerItem("GEOCRYSTAL", new Item(new QuiltItemSettings()));
	public static final Item TOXINBITE = registerItem("TOXINBITE", new Item(new QuiltItemSettings()));
	public static final Item SOLARITE = registerItem("SOLARITE", new Item(new QuiltItemSettings()));
	public static final Item BRIMSTONE = registerItem("BRIMSTONE", new Item(new QuiltItemSettings()));
	public static final Item CRYPTOLITE = registerItem("CRYPTOLITE", new Item(new QuiltItemSettings()));
	public static final Item PYROFUME = registerItem("PYROFUME", new Item(new QuiltItemSettings()));
	public static final Item LUMINSTONE = registerItem("LUMINSTONE", new Item(new QuiltItemSettings()));
	public static final Item MYSTICORE = registerItem("MYSTICORE", new Item(new QuiltItemSettings()));
	public static final Item GEMSPARK = registerItem("GEMSPARK", new Item(new QuiltItemSettings()));
	public static final Item NETHERIUM = registerItem("NETHERIUM", new Item(new QuiltItemSettings()));
	public static final Item MOLYFORGE = registerItem("MOLYFORGE", new Item(new QuiltItemSettings()));
	public static final Item TECHNEON = registerItem("TECHNEON", new Item(new QuiltItemSettings()));
	public static final Item STARSHARD = registerItem("STARSHARD", new Item(new QuiltItemSettings()));
	public static final Item RHODITE = registerItem("RHODITE", new Item(new QuiltItemSettings()));
	public static final Item PALLADUST = registerItem("PALLADUST", new Item(new QuiltItemSettings()));
	public static final Item ARGENTUM = registerItem("ARGENTUM", new Item(new QuiltItemSettings()));
	public static final Item LUMINIUM = registerItem("LUMINIUM", new Item(new QuiltItemSettings()));
	public static final Item INDIGEM = registerItem("INDIGEM", new Item(new QuiltItemSettings()));
	public static final Item TINFORGE = registerItem("TINFORGE", new Item(new QuiltItemSettings()));
	public static final Item VENOMITE = registerItem("VENOMITE", new Item(new QuiltItemSettings()));
	public static final Item TELLUBRIGHT = registerItem("TELLUBRIGHT", new Item(new QuiltItemSettings()));
	public static final Item IRIDESCENTITE = registerItem("IRIDESCENTITE", new Item(new QuiltItemSettings()));
	public static final Item XENOLIGHT = registerItem("XENOLIGHT", new Item(new QuiltItemSettings()));
	public static final Item PYROSURGE = registerItem("PYROSURGE", new Item(new QuiltItemSettings()));
	public static final Item RADIANCESTONE = registerItem("RADIANCESTONE", new Item(new QuiltItemSettings()));
	public static final Item MAGUSITE = registerItem("MAGUSITE", new Item(new QuiltItemSettings()));
	public static final Item CELESTIUM = registerItem("CELESTIUM", new Item(new QuiltItemSettings()));
	public static final Item PRISMATICORE = registerItem("PRISMATICORE", new Item(new QuiltItemSettings()));
	public static final Item LUSTRONITE = registerItem("LUSTRONITE", new Item(new QuiltItemSettings()));
	public static final Item ENERGONIUM = registerItem("ENERGONIUM", new Item(new QuiltItemSettings()));
	public static final Item AURALITE = registerItem("AURALITE", new Item(new QuiltItemSettings()));
	public static final Item EUROCRYSTAL = registerItem("EUROCRYSTAL", new Item(new QuiltItemSettings()));
	public static final Item GEMINITE = registerItem("GEMINITE", new Item(new QuiltItemSettings()));
	public static final Item TERRESTEEL = registerItem("TERRESTEEL", new Item(new QuiltItemSettings()));
	public static final Item DRACONITE = registerItem("DRACONITE", new Item(new QuiltItemSettings()));
	public static final Item HARMONIUM = registerItem("HARMONIUM", new Item(new QuiltItemSettings()));
	public static final Item GEMERALD = registerItem("GEMERALD", new Item(new QuiltItemSettings()));
	public static final Item ETHERTIDE = registerItem("ETHERTIDE", new Item(new QuiltItemSettings()));
	public static final Item SPECTRONITE = registerItem("SPECTRONITE", new Item(new QuiltItemSettings()));
	public static final Item LUCENTIUM = registerItem("LUCENTIUM", new Item(new QuiltItemSettings()));
	public static final Item PLASMIUM = registerItem("PLASMIUM", new Item(new QuiltItemSettings()));
	public static final Item MISTICORE = registerItem("MISTICORE", new Item(new QuiltItemSettings()));
	public static final Item WOLFRAMITE = registerItem("WOLFRAMITE", new Item(new QuiltItemSettings()));
	public static final Item RHEOFLUX = registerItem("RHEOFLUX", new Item(new QuiltItemSettings()));
	public static final Item OSMISTONE = registerItem("OSMISTONE", new Item(new QuiltItemSettings()));
	public static final Item IRIDESPIRE = registerItem("IRIDESPIRE", new Item(new QuiltItemSettings()));
	public static final Item PLATINAURUM = registerItem("PLATINAURUM", new Item(new QuiltItemSettings()));
	public static final Item QUICKSILVA = registerItem("QUICKSILVA", new Item(new QuiltItemSettings()));
	public static final Item RADIOLITE = registerItem("RADIOLITE", new Item(new QuiltItemSettings()));
	public static final Item LEADTIDE = registerItem("LEADTIDE", new Item(new QuiltItemSettings()));
	public static final Item PRISMABITE = registerItem("PRISMABITE", new Item(new QuiltItemSettings()));
	public static final Item POLONITE = registerItem("POLONITE", new Item(new QuiltItemSettings()));
	public static final Item NEBULITE = registerItem("NEBULITE", new Item(new QuiltItemSettings()));
	public static final Item RADIONITE = registerItem("RADIONITE", new Item(new QuiltItemSettings()));
	public static final Item VOLCANIUM = registerItem("VOLCANIUM", new Item(new QuiltItemSettings()));
	public static final Item RADITE = registerItem("RADITE", new Item(new QuiltItemSettings()));
	public static final Item ACTINASTONE = registerItem("ACTINASTONE", new Item(new QuiltItemSettings()));
	public static final Item THORINITE = registerItem("THORINITE", new Item(new QuiltItemSettings()));
	public static final Item PROTOMYST = registerItem("PROTOMYST", new Item(new QuiltItemSettings()));
	public static final Item NAUTICALITE = registerItem("NAUTICALITE", new Item(new QuiltItemSettings()));
	public static final Item PLUTONIUM = registerItem("PLUTONIUM", new Item(new QuiltItemSettings()));
	public static final Item STARSTRUCKITE = registerItem("STARSTRUCKITE", new Item(new QuiltItemSettings()));
	public static final Item CURIOFLUX = registerItem("CURIOFLUX", new Item(new QuiltItemSettings()));
	public static final Item QUANTUMITE = registerItem("QUANTUMITE", new Item(new QuiltItemSettings()));
	public static final Item CALIOPTRON = registerItem("CALIOPTRON", new Item(new QuiltItemSettings()));
	public static final Item EINSTARITE = registerItem("EINSTARITE", new Item(new QuiltItemSettings()));
	public static final Item FERMETRON = registerItem("FERMETRON", new Item(new QuiltItemSettings()));
	public static final Item MENDELSTONE = registerItem("MENDELSTONE", new Item(new QuiltItemSettings()));
	public static final Item NOBELLITE = registerItem("NOBELLITE", new Item(new QuiltItemSettings()));
	public static final Item LAWRENCITE = registerItem("LAWRENCITE", new Item(new QuiltItemSettings()));
	public static final Item RUTHERFORDIUM = registerItem("RUTHERFORDIUM", new Item(new QuiltItemSettings()));
	public static final Item DUBNIUM = registerItem("DUBNIUM", new Item(new QuiltItemSettings()));
	public static final Item SEABORITE = registerItem("SEABORITE", new Item(new QuiltItemSettings()));
	public static final Item BOHRSTONE = registerItem("BOHRSTONE", new Item(new QuiltItemSettings()));
	public static final Item HASSISURGE = registerItem("HASSISURGE", new Item(new QuiltItemSettings()));
	public static final Item MEITNERIUM = registerItem("MEITNERIUM", new Item(new QuiltItemSettings()));
	public static final Item DARMSTADIUM = registerItem("DARMSTADIUM", new Item(new QuiltItemSettings()));
	public static final Item ROENTGENIUM = registerItem("ROENTGENIUM", new Item(new QuiltItemSettings()));
	public static final Item COPERNICITE = registerItem("COPERNICITE", new Item(new QuiltItemSettings()));
	public static final Item NIHONITE = registerItem("NIHONITE", new Item(new QuiltItemSettings()));
	public static final Item FLEROVIUM = registerItem("FLEROVIUM", new Item(new QuiltItemSettings()));
	public static final Item MOSCOVITE = registerItem("MOSCOVITE", new Item(new QuiltItemSettings()));
	public static final Item LUMINITIUM = registerItem("LUMINITIUM", new Item(new QuiltItemSettings()));
	public static final Item TENNELITE = registerItem("TENNELITE", new Item(new QuiltItemSettings()));
	public static final Item OGANITE = registerItem("OGANITE", new Item(new QuiltItemSettings()));


	private static Item registerItem(String name, Item item) {
		return Registry.register(Registries.ITEM, new Identifier(ChroniteCore.MOD_ID, name), item);
	}
	public static void registerModItems() {
		ChroniteCore.LOGGER.info("Starting Mod Items for " + ChroniteCore.MOD_ID);
	}
}
